-- PROJECT
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Excel Peer Support Network', 60, 'Excel (www.excel.gatech.edu) is a four-year, dual certificate program for students with intellectual and developmental disabilities. The Peer Support Network is designed to provide the individualized support necessary for Excel students to thrive at Georgia Tech. ', 'Marnie', 'Williams', 'mwilliams@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('ESW Hydroponics/Urban Farming Project', 7, 'The Hydroponics/Urban Farming Project experiments with different ways to grow produce in urban areas using limited space and water resources. We investigate both soil-based and hydroponic methods of growing in order to find the most efficient, economically viable, and environmentally sustainable way to grow produce in Atlanta. ', 'Nicole', 'Kinnard', 'nkinnard@gatech.edu', 'Sustainable Communities');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Excel Current Events', 15, 'Excel Current Events is a participation (not for credit) course for degree-seeking students who are interested in developing their communication skills in conversations with adults with intellectual and developmental disabilities. ', 'Ashley', 'Bidlack', 'abidlack@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Shakespeare in Prison Project', 20, 'As the world celebrates the 400th anniversary of Shakespeare’s death in 2016, Georgia Tech students will travel to a high-security men’s prison outside Atlanta to discuss Shakespeare with incarcerated students. ', 'Sarah', 'Higinbotham', 'shiginbotham@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Know Your Water Project', 10, 'This project will allow students to be part of a large, crowd-sourced study – at little cost to themselves – to contribute to a knowledge bank of how different communities treat and track their water quality. If you are interested in participating in this study, please let us know. ', 'Neha', 'Kumar', 'nkumar@gatech.edu', 'Sustainable Communities');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Epic Intentions', 20, 'Epic Intentions connects an interdisciplinary team of students with a local nonprofit to apply technical skills for social and civic good to help make the nonprofits make a greater impact in the community.', 'Yeji', 'Lee', 'ylee@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Acromantula', 60, 'Follow the spiders.', 'Rubeus', 'Hagrid', 'hagrid@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Basilisk', 7, 'Only the Heir of Slytherin can open the Chamber of Secrets', 'Tom', 'Riddle', 'voldemort@gatech.edu', 'Sustainable Communities');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Centaur', 15, 'This is where I leave you. You are safe now. Good luck, Harry Potter. The planets have been read wrongly before now, even by centaurs. I hope this is one of those times.', 'Firenze', 'Woodsman', 'centaur@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Dragon', 20, 'Accio Firebolt!', 'Hungarian', 'Horntail', 'dragon@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Ghoul', 10, 'In wizarding families the ghoul often becomes a talking point or even a family pet.', 'Ronald', 'Weasley', 'ghoul@gatech.edu', 'Sustainable Communities');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Leprechaun', 20, 'Leprechaun gold has the quality of disappearing after a few hours.', 'Ludo', 'Bagman', 'bagman@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Merperson', 60, 'Try opening it under the water.', 'Moaning', 'Myrtle', 'myrtle@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Three-headed Dog', 7, 'Guard the Philosophers Stone.', 'Fluffy', 'Guard', 'fluffy@gatech.edu', 'Sustainable Communities');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Toad', 15, 'Croak.', 'Trevor', 'Croak', 'trevor@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Troll', 20, 'Anyone can speak troll. All you have to do is point and grunt.', 'Point', 'Grunt', 'troll@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Thestral', 10, 'They can only be seen by people who have seen death.', 'Cedric', 'Diggory', 'cedric@gatech.edu', 'Sustainable Communities');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Hippogriff', 20, 'Buckbeak was a good hippogriff, always cleaned his feathers.', 'Buckbeak', 'Witherwings', 'buckbeak@gatech.edu', 'Community');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Owl', 10, 'Harry now carried a large cage that held a beautiful snowy owl, fast asleep with her head under her wing.', 'Hedwig', 'Snowy', 'hedwig@gatech.edu', 'Sustainable Communities');
INSERT INTO project (name, estNum, description, advfName, advlName, advEmail, desigName) VALUES ('Unicorn', 20, 'You have slain something pure and defenceless to save yourself, and you will have but a half-life, a cursed life, from the moment the blood touches your lips.', 'Quirinus ', 'Quirrell', 'unicorn@gatech.edu', 'Community');

-- PROJECT CATEGORY
INSERT INTO project_category (projectName, categoryName) VALUES ('Excel Peer Support Network', 'computing for good');
INSERT INTO project_category (projectName, categoryName) VALUES ('Excel Peer Support Network', 'doing good for your neighborhood');
INSERT INTO project_category (projectName, categoryName) VALUES ('Excel Peer Support Network', 'reciprocal teaching and learning');
INSERT INTO project_category (projectName, categoryName) VALUES ('ESW Hydroponics/Urban Farming Project', 'urban development');
INSERT INTO project_category (projectName, categoryName) VALUES ('ESW Hydroponics/Urban Farming Project', 'sustainable communities');
INSERT INTO project_category (projectName, categoryName) VALUES ('Excel Current Events', 'computing for good');
INSERT INTO project_category (projectName, categoryName) VALUES ('Excel Current Events', 'doing good for your neighborhood');
INSERT INTO project_category (projectName, categoryName) VALUES ('Excel Current Events', 'reciprocal teaching and learning');
INSERT INTO project_category (projectName, categoryName) VALUES ('Excel Current Events', 'technology for social good');
INSERT INTO project_category (projectName, categoryName) VALUES ('Shakespeare in Prison Project', 'urban development');
INSERT INTO project_category (projectName, categoryName) VALUES ('Shakespeare in Prison Project', 'sustainable communities');
INSERT INTO project_category (projectName, categoryName) VALUES ('Know Your Water Project', 'sustainable communities');
INSERT INTO project_category (projectName, categoryName) VALUES ('Know Your Water Project', 'crowd sourced');
INSERT INTO project_category (projectName, categoryName) VALUES ('Epic Intentions', 'doing good for your neighborhood');
INSERT INTO project_category (projectName, categoryName) VALUES ('Epic Intentions', 'collaborative action');
INSERT INTO project_category (projectName, categoryName) VALUES ('Acromantula', 'doing good for your neighborhood');
INSERT INTO project_category (projectName, categoryName) VALUES ('Acromantula', 'collaborative action');
INSERT INTO project_category (projectName, categoryName) VALUES ('Basilisk', 'sustainable communities');
INSERT INTO project_category (projectName, categoryName) VALUES ('Basilisk', 'crowd sourced');
INSERT INTO project_category (projectName, categoryName) VALUES ('Centaur', 'sustainable communities');
INSERT INTO project_category (projectName, categoryName) VALUES ('Centaur', 'crowd sourced');
INSERT INTO project_category (projectName, categoryName) VALUES ('Dragon', 'sustainable communities');
INSERT INTO project_category (projectName, categoryName) VALUES ('Dragon', 'crowd sourced');
INSERT INTO project_category (projectName, categoryName) VALUES ('Ghoul', 'sustainable communities');
INSERT INTO project_category (projectName, categoryName) VALUES ('Leprechaun', 'sustainable communities');
INSERT INTO project_category (projectName, categoryName) VALUES ('Merperson', 'sustainable communities');
INSERT INTO project_category (projectName, categoryName) VALUES ('Three-headed Dog', 'computing for good');
INSERT INTO project_category (projectName, categoryName) VALUES ('Toad', 'computing for good');
INSERT INTO project_category (projectName, categoryName) VALUES ('Troll', 'computing for good');
INSERT INTO project_category (projectName, categoryName) VALUES ('Thestral', 'computing for good');
INSERT INTO project_category (projectName, categoryName) VALUES ('Hippogriff', 'computing for good');
INSERT INTO project_category (projectName, categoryName) VALUES ('Owl', 'computing for good');
INSERT INTO project_category (projectName, categoryName) VALUES ('Unicorn', 'computing for good');
