-- COURSE
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('ARCH 4803', 'Green Infrastructure: EPA Campus Rainwater Challenge', 'Richard', 'Dagenhart', 'Sustainable Communities', '26');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('BMED 2250', 'Problems in Biomedical Engineering', 'Barbara Burks', 'Fasse', 'Community', '300');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('PUBP 3315', 'Environmental Policy and Politics', 'Alice', 'Favero', 'Sustainable Communities', '25');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('EAS 2803', 'Urban Forest', 'Monica', 'Halka', 'Sustainable Communities', '10');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('BIOL 1511', 'Honors Biological Principles; Honors Organismal Biology', 'Brian', 'Hammer', 'Sustainable Communities', '150');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('EAS 1600', 'Introduction to Environmental Science', 'Dana', 'Hartley', 'Community', '600');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('EAS 1601', 'Habitable Planet', 'Dana', 'Hartley', 'Community', '600');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('EAS 2750', 'Physics of the Weather', 'Dana', 'Hartley', 'Community', '30');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('EAS 1000', 'The Earth', 'Greg', 'Huey', 'Sustainable Communities', '26');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('EAS 2000', 'The (Reverse) Sun', 'Harrison', 'Wells', 'Community', '300');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('EAS 3000', 'Vibrations', 'Cisco', 'Ramon', 'Sustainable Communities', '52');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('EAS 4000', 'The Speed Force', 'Barry', 'Allen', 'Sustainable Communities', '52');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('BMED 1000', 'Healing', 'Oliver', 'Queen', 'Sustainable Communities', '150');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('BMED 2000', 'Watching', 'Felicity', 'Smoak', 'Community', '600');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('BMED 3000', 'Islands', 'Slade', 'Wilson', 'Community', '600');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('BMED 4000', 'Alloys', 'Ray', 'Palmer', 'Community', '30');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('CS 1301', 'Python', 'Jay', 'Summet', 'Sustainable Communities', '150');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('CS 2200', 'Systems and Networks', 'Tom', 'Conte', 'Sustainable Communities', '151');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('CS 3600', 'AI', 'Jim', 'Rehg', 'Sustainable Communities', '152');
INSERT INTO course (courseNumber, name, instructorfName, instructorlName, designation, estNumberStudents) VALUES ('CS 4400', 'Databases', 'Monica', 'Sweat', 'Sustainable Communities', '153');

-- COURSE CATEGORY
INSERT INTO course_category (courseNumber, categoryName) VALUES ('ARCH 4803', 'computing for good');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('ARCH 4803', 'doing good for your neighborhood');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('BMED 2250', 'computing for good');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('BMED 2250', 'doing good for your neighborhood');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('PUBP 3315', 'urban development');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('PUBP 3315', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 2803', 'urban development');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 2803', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('BIOL 1511', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 1600', 'urban development');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 1600', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 1601', 'urban development');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 1601', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 2750', 'urban development');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 2750', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 1000', 'urban development');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 1000', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 2000', 'urban development');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 2000', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 3000', 'urban development');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 3000', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('EAS 4000', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('BMED 1000', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('BMED 2000', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('BMED 3000', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('BMED 4000', 'sustainable communities');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('CS 1301', 'computing for good');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('CS 2200', 'computing for good');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('CS 3600', 'computing for good');
INSERT INTO course_category (courseNumber, categoryName) VALUES ('CS 4400', 'computing for good');
